// <auto-generated />
namespace Profile_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class location4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(location4));
        
        string IMigrationMetadata.Id
        {
            get { return "202503250945113_location=4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
