// <auto-generated />
namespace Profile_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class role_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202503140144315_role_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
